const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const cp=require('node:child_process');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const base='fbe5b5e0c961e125ad8f0227c55c7d82302b7cda';
function runtime(seed, original=false){
 const memory=new Map(seed?Object.entries(seed):[]),nodes=new Map(),errors=[];
 const element=()=>({value:'',hidden:false,textContent:'',innerHTML:'',dataset:{},style:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},setAttribute(){},getAttribute(){return null},appendChild(){},querySelectorAll(){return [element(),element()]},querySelector(){return element()},focus(){},remove(){},click(){}});
 const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
 for(const [,id] of html.matchAll(/\bid="([^"]+)"/g))nodes.set(id,element());
 const document={getElementById:id=>nodes.get(id)||null,querySelectorAll:()=>[],querySelector:()=>null,createElement:element,createTreeWalker:()=>({nextNode:()=>null}),body:element(),documentElement:element(),addEventListener(){}};
 const localStorage={getItem:k=>memory.get(k)??null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k),key:i=>[...memory.keys()][i],get length(){return memory.size}};
 const ctx=vm.createContext({console:{...console,error:(...x)=>errors.push(x.join(' ')),warn(){}},structuredClone,Date,URL,Request,Response,Blob,Map,Set,Intl,document,NodeFilter:{SHOW_TEXT:4,FILTER_REJECT:2,FILTER_ACCEPT:1},localStorage,navigator:{},location:{href:'https://test.invalid/Tracker/'},setTimeout:()=>0,clearTimeout(){},setInterval(){},addEventListener(){},alert(){},confirm:()=>true});
 ctx.window=ctx;
 const run=s=>vm.runInContext(s,ctx);
 if(original){
  const html=cp.execFileSync('git',['show',base+':index.html'],{cwd:root,encoding:'utf8'});
  run(cp.execFileSync('git',['show',base+':today.js'],{cwd:root,encoding:'utf8'}));
  run(fs.readFileSync(path.join(root,'habits.js'),'utf8'));
  run(html.match(/<script>([\s\S]*?)<\/script>/)[1].split("if('serviceWorker'in navigator)")[0]);
 }else for(const f of ['today.js','habits.js','dates.js','storage.js','app.js'])run(fs.readFileSync(path.join(root,f),'utf8').split("if('serviceWorker'in navigator)")[0]);
 return {run,nodes,memory,errors,ctx,json:s=>JSON.parse(run(`JSON.stringify(${s})`))};
}
function fixture(){return {schemaVersion:2,smokeDate:'2022-02-02',alcoholDate:'2023-03-03',alcoholTrackingStart:'2021-01-01',alcoholHistory:{'2023-03-02':true},bodyMeasurements:{'2023-03-03':{waist:81.2,thigh:null}},logs:{'2023-03-03':{protein:0,steps:1234,gym:false,sleep:null,weight:75.5,outdoors:'',habitDetails:{walks:[{id:'synthetic',minutes:10}]}},'2023-03-04':{gym:true,english_general:35}},trackers:[{id:'custom',goal:5},{id:'water',goal:2}],englishLearning:{customItems:[{id:'custom_1',title:'Synthetic item',kind:'word'}],review:{custom_1:{nextReview:'2023-03-05',lastReviewed:'2023-03-03'}},favorites:{custom_1:true},dailyQueue:{date:'2023-03-03',itemIds:['custom_1'],newItemIds:[],extension:'keep'},studyPlans:{sample:{answers:['saved answer']}},extension:'keep'},experiments:[{id:'sample',name:'Test',metric:'steps',target:1000,days:30,start:'2023-03-03'}],theme:'light',language:'en',motivationSeen:{sample:'seen'},lastExternalBackupAt:'2023-03-03T00:00:00Z',_storageMeta:{revision:20,savedAt:'2023-03-03T00:00:00Z',extra:'keep'},extra:{keep:true}}}
test('clean install has no personal records or fixed personal dates',()=>{const r=runtime();for(const k of ['logs','alcoholHistory','bodyMeasurements','motivationSeen'])assert.deepEqual(r.json(`data.${k}`),{});assert.equal(r.run('data.smokeDate'),'');assert.equal(r.run('data.alcoholDate'),'');assert.equal(r.run('data.alcoholTrackingStart'),r.run('localDate()'));});
test('saved schema v2 retains every field, missing value and legacy tracker',()=>{const f=fixture(),r=runtime({'my-life-tracker-data':JSON.stringify(f)}),d=r.json('data');for(const k of Object.keys(f)){if(k==='trackers')assert.deepEqual(d[k].slice(0,f[k].length),f[k]);else assert.deepEqual(d[k],f[k],k)}assert.equal(d.schemaVersion,2);});
test('actual current app save upgrades without losing persisted data',()=>{const old=runtime(undefined,true);old.run('writeLocalCopies(data)');const before=old.json('data'),now=runtime(Object.fromEntries(old.memory));assert.deepEqual(now.json('data'),before);});
test('legacy v0 and v1 numeric zero goals survive migration; missing personal history stays empty',()=>{for(const version of [0,1]){const r=runtime();r.ctx.raw={schemaVersion:version,logs:{},sleepGoal:0,gymGoal:0};const d=r.json('migrateData(raw)');assert.equal(d.sleepGoal,0);assert.equal(d.gymGoal,0);assert.deepEqual(d.bodyMeasurements,{});assert.deepEqual(d.alcoholHistory,{})}});
test('newer mirror wins; corrupted primary and unrelated object do not replace records',()=>{const f=fixture();const r=runtime({'my-life-tracker-data':'{bad','my-life-tracker-data-mirror-v1':JSON.stringify(f),'rhythm-preferences':JSON.stringify({theme:'dark'})});assert.deepEqual(r.json('data.logs'),f.logs);assert.equal(r.run('parseCandidate("x","[]")'),null);assert.equal(r.run('parseCandidate("x",JSON.stringify({hello:true}))'),null);});
test('newer intentional deletion beats older larger recovery copy',()=>{const r=runtime();r.ctx.old=fixture();r.ctx.fresh={...fixture(),logs:{},_storageMeta:{revision:21,savedAt:'2023-03-04T00:00:00Z'}};assert.equal(r.run('bestCandidate([{key:"old",data:old},{key:"fresh",data:fresh}]).key'),'fresh');});
test('backup envelope/raw roundtrip and malformed backup rejection',()=>{const r=runtime();r.ctx.f=fixture();assert.deepEqual(r.json('validateBackupObject({format:"my-life-tracker-backup",data:f})'),r.json('migrateData(f)'));assert.deepEqual(r.json('validateBackupObject(f)'),r.json('migrateData(f)'));for(const bad of [[],{}, {format:'my-life-tracker-backup',data:[]},{logs:[]},{logs:{bad:null}},{trackers:[null]}]){r.ctx.bad=bad;assert.throws(()=>r.run('validateBackupObject(bad)'))}});
test('trends and weekly averages distinguish missing, boolean and numeric zero',()=>{const r=runtime();r.run('data.logs={a:{steps:null,gym:null},b:{steps:"",gym:false},c:{steps:false},d:{steps:0},e:{steps:100}}');assert.deepEqual(r.json('["a","b","c","d","e"].map(k=>trendValueForDay("steps",k))'),[null,null,null,0,100]);assert.equal(r.run('trendValueForDay("gym","a")'),null);assert.equal(r.run('trendValueForDay("gym","b")'),0);assert.equal(r.run('weeklyNumericStats("steps",["a","b","c","d","e"]).avg'),50);});
test('DST, leap year, month and Monday boundaries use calendar days',()=>{const r=runtime();assert.equal(r.run('weeklyDiffDays("2024-09-28","2024-09-30")'),2);assert.equal(r.run('weeklyAddDays("2024-02-28",1)'),'2024-02-29');assert.equal(r.run('weeklyAddDays("2024-12-31",1)'),'2025-01-01');assert.equal(r.run('weeklyMonday("2024-03-03")'),'2024-02-26');});
test('Home streak matches calendar and preserves explicit drinking semantics',()=>{const r=runtime();r.run('data.alcoholTrackingStart="2024-09-28";data.alcoholHistory={};alcoholTodayKey=()=>"2024-09-30"');assert.equal(r.run('alcoholCurrentStreakDays()'),2);assert.equal(r.run('todayAlcoholFreeDays("2024-09-30")'),2);r.run('data.alcoholHistory["2024-09-29"]=true');assert.equal(r.run('todayAlcoholFreeDays("2024-09-30")'),0);assert.equal(r.run('todayAlcoholFreeDays("2024-10-01")'),1);});
test('body check-in create/edit/delete preserves other metrics and does not create zeros',()=>{const r=runtime();r.run('persistData=()=>{};renderBody=()=>{};data.logs["2023-03-03"]={steps:123};openBodyCheckin("2023-03-03")');r.nodes.get('bodyWaistInput').value='80.5';r.run('saveBodyCheckin()');assert.deepEqual(r.json('data.bodyMeasurements["2023-03-03"]'),{waist:80.5});assert.deepEqual(r.json('data.logs["2023-03-03"]'),{steps:123});r.run('openBodyCheckin("2023-03-03")');r.nodes.get('bodyWaistInput').value='81';r.run('saveBodyCheckin()');assert.equal(r.run('data.bodyMeasurements["2023-03-03"].waist'),81);r.run('openBodyCheckin("2023-03-03");deleteBodyCheckin()');assert.equal(r.run('data.bodyMeasurements["2023-03-03"]'),undefined);assert.equal(r.run('data.logs["2023-03-03"].steps'),123);});
test('history Today rejects future/invalid dates; numeric and boolean editing persist values',()=>{const r=runtime();r.run('renderToday=()=>{};persistData=()=>{};setTodayDate("2023-02-30")');assert.equal(r.run('todaySelectedDate'),null);r.run('setTodayDate("2023-03-03");openEntry("protein","2023-03-03")');r.nodes.get('entryValue').value='0';r.run('saveEntry();openTodayMetric("gym","2023-03-03")');assert.equal(r.run('data.logs["2023-03-03"].protein'),0);assert.equal(r.run('data.logs["2023-03-03"].gym'),true);});
test('habit editing saves selected day and preserves blank duration',()=>{const r=runtime();for(const id of ['habitDuration','habitAsleep','habitWake','habitSleepPreview'])r.nodes.set(id,{value:'',textContent:''});r.run('persistData=()=>{};data.logs["2023-03-03"]={sleep:7.5};openHabitEditor("sleep","2023-03-03")');r.nodes.get('habitDuration').value='';r.nodes.get('habitAsleep').value='23:00';r.nodes.get('habitWake').value='07:00';r.run('saveHabitEditor()');assert.equal(r.run('data.logs["2023-03-03"].sleep'),7.5);assert.equal(r.run('habitSleepSpan("23:00","07:00")'),480);});
test('English queue stays stable on same day and preserves review/study state',()=>{const r=runtime();r.run('ensureEnglishDailyQueue("2023-03-03")');const first=r.json('data.englishLearning.dailyQueue');r.run('ensureEnglishDailyQueue("2023-03-03")');assert.deepEqual(r.json('data.englishLearning.dailyQueue'),first);assert.ok(first.itemIds.length>0);r.run('data.englishLearning.studyPlans={sample:{answer:"keep"}};ensureEnglishDailyQueue("2023-03-04")');assert.equal(r.run('data.englishLearning.studyPlans.sample.answer'),'keep');});
test('user text and IDs are escaped for HTML and JavaScript attribute contexts',()=>{const r=runtime();assert.equal(r.run('escapeHTML("<img onerror=x>")'),'&lt;img onerror=x&gt;');r.ctx.attack="x');alert(1);//\"";const encoded=r.run('inlineArgument(attack)');assert.ok(!encoded.includes('"'));assert.ok(!encoded.includes("'"));});
test('asynchronous recovery picks newest vault and rechecks concurrent memory edits',async()=>{const r=runtime();r.ctx.f=fixture();r.run('vaultReadCurrent=async()=>({data:f});vaultReadSnapshots=async()=>[];vaultReadCache=async()=>null;writeVaultCopies=async()=>{};render=()=>{}');await r.run('recoverFromVaults()');assert.deepEqual(r.json('data.logs'),fixture().logs);r.run('vaultReadCurrent=async()=>{data.logs={synthetic:{steps:9}};data._storageMeta={savedAt:"2030-01-01T00:00:00Z",revision:50};return {data:f}}');await r.run('recoverFromVaults()');assert.equal(r.run('data.logs.synthetic.steps'),9);});
test('vault writes run in invocation order and capture immutable snapshots',async()=>{const r=runtime();r.run('var seen=[];writeVaultCopiesNow=async payload=>{seen.push(payload.value)};var p={value:1};var one=writeVaultCopies(p);p.value=2;var two=writeVaultCopies(p)');await r.run('Promise.all([one,two])');assert.deepEqual(r.json('seen'),[1,2]);});

test('render entry points execute against expected DOM IDs without runtime errors',()=>{const r=runtime();for(const fn of ['renderToday','renderEnglish','renderProgress','renderSettings','renderBody','renderAlcoholCalendar','renderWeeklyReview'])r.run(fn+'()');assert.deepEqual(r.errors,[])});
test('invalid body measurement does not silently delete an existing record',()=>{const r=runtime();r.run('data.bodyMeasurements["2023-03-03"]={waist:80,extension:"keep"};openBodyCheckin("2023-03-03")');r.nodes.get('bodyWaistInput').value='-2';r.run('saveBodyCheckin()');assert.equal(r.run('data.bodyMeasurements["2023-03-03"].waist'),80);});
test('English rating schedules review and study answers persist locally',()=>{const r=runtime();r.run('persistData=()=>{};englishRateItem("word_figure_out","know")');assert.equal(r.run('data.englishLearning.review.word_figure_out.nextReview'),r.run('weeklyAddDays(localDate(),3)'));r.run('saveEnglishPlanAnswer("session-1","1a",0,"synthetic answer")');assert.ok(r.memory.get('my-life-tracker-data').includes('synthetic answer'));r.run('englishRateItem("word_figure_out","again")');assert.equal(r.run('data.englishLearning.review.word_figure_out.nextReview'),r.run('localDate()'));});
test('theme/language toggles and rollover retain records',()=>{const r=runtime({'my-life-tracker-data':JSON.stringify(fixture())});r.run('save=()=>{};toggleTheme();toggleLanguage()');assert.equal(r.run('data.theme'),'dark');assert.equal(r.run('data.language'),'ru');r.run('persistEnglishDailyQueueQuietly=()=>{};appActiveDate="2000-01-01";checkAppDayRollover()');assert.deepEqual(r.json('data.logs'),fixture().logs);});
test('chart ranges handle empty, single, sparse and long histories',()=>{const r=runtime();for(const logs of [{},{'2023-01-01':{weight:70}},{'2021-01-01':{weight:70},'2025-02-01':{weight:72}}]){r.ctx.logs=logs;r.run('data.logs=logs');for(const range of [7,30,90,365,'all']){r.ctx.range=range;r.run('trendRangeDays=range;renderTrends();bodyRangeDays=range;renderBody()')}}assert.deepEqual(r.errors,[]);});
test('service worker precaches every linked asset and preserves data vault on activation',async()=>{const handlers={},deleted=[],added=[];const cache={addAll:async xs=>added.push(...xs),match:async()=>undefined,put:async()=>{}};const context=vm.createContext({URL,Request,Response,Set,self:{location:{origin:'https://test.invalid'},registration:{scope:'https://test.invalid/Tracker/'},clients:{claim:async()=>{}},skipWaiting:async()=>{},addEventListener:(e,f)=>handlers[e]=f},caches:{open:async()=>cache,keys:async()=>['my-rhythm-v-old','life-tracker-app-old','my-rhythm-data-vault-v1','unrelated'],delete:async k=>deleted.push(k)},fetch:async()=>new Response('network')});vm.runInContext(fs.readFileSync(path.join(root,'sw.js'),'utf8'),context);let pending;handlers.install({waitUntil:p=>pending=p});await pending;for(const req of added){const local=new URL(req.url).pathname.replace('/Tracker/','');assert.ok(fs.existsSync(path.join(root,local||'index.html')),local)}const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const [,src] of html.matchAll(/(?:src|href)="([^"#]+\.(?:js|css)(?:\?[^"]*)?)"/g))assert.ok(added.some(r=>new URL(r.url).pathname.endsWith(src.split('?')[0])),src);handlers.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(deleted,['my-rhythm-v-old','life-tracker-app-old']);let responded=false;handlers.fetch({request:new Request('https://test.invalid/Tracker/__my_rhythm_data_vault_v1__.json'),respondWith(){responded=true}});assert.equal(responded,false);cache.match=async()=>new Response('offline');context.fetch=async()=>{throw Error('offline')};handlers.fetch({request:new Request('https://test.invalid/Tracker/app.js?v=6111'),respondWith:p=>pending=p});assert.equal(await (await pending).text(),'offline');context.fetch=async()=>new Response('error',{status:500});handlers.fetch({request:new Request('https://test.invalid/Tracker/app.js?v=6111'),respondWith:p=>pending=p});assert.equal(await (await pending).text(),'offline');});
test('alcohol mark/unmark changes only explicit drinking history',()=>{const r=runtime();r.run('persistData=()=>{};renderAlcoholCalendar=()=>{};data.alcoholTrackingStart="2023-01-01";toggleAlcoholDay("2023-03-03")');assert.equal(r.run('data.alcoholHistory["2023-03-03"]'),true);r.run('toggleAlcoholDay("2023-03-03")');assert.equal(r.run('data.alcoholHistory["2023-03-03"]'),undefined);assert.deepEqual(r.json('data.logs'),{});});
test('English custom content can be added and rendered as text',()=>{const r=runtime();r.run('persistData=()=>{};renderEnglishLearning=()=>{}');r.nodes.get('englishAddKind').value='word';r.nodes.get('englishAddTerm').value='<b>synthetic</b>';r.nodes.get('englishAddMeaning').value='Example';r.run('saveEnglishCustomItem()');assert.equal(r.run('data.englishLearning.customItems[0].title'),'<b>synthetic</b>');assert.equal(r.run('escapeHTML(data.englishLearning.customItems[0].title)'),'&lt;b&gt;synthetic&lt;/b&gt;');});
